<?php

namespace Connectum\Models\Operations;

use Connectum\Models\AbstractModel;
use Connectum\Entity\Custom\OperationsListEntityMain;

class OperationsList extends AbstractModel
{
    protected $method = 'GET';
    protected $pathToMainData = 'tasks->{$postID}->result';
    protected $requestToFunction = '/operations/';


    /**
     * @param string $expand
     * @return $this
     */
    public function setExpand(string $expand)
    {
        $this->payload['expand'] = $expand;
        return $this;
    }

    /**
     * @param string $status
     * @return $this
     */
    public function setStatus(string $status)
    {
        $this->payload['status'] = $status;
        return $this;
    }

    public function setType(string $type)
    {
        $this->payload['type'] = $type;
        return $this;
    }

    /**
     * @param string|null $from
     * @param string|null $to
     * @return $this
     */
    public function setFilterDate(?string $from = null, ?string $to = null)
    {
        if ($from !== null)
            $this->payload['created_from'] = $from;

        if ($to !== null)
            $this->payload['created_to'] = $to;

        return $this;
    }


    public function get(): OperationsListEntityMain
    {
        return parent::get(); // TODO: Change the autogenerated stub
    }
}
