<?php

namespace Connectum\Models\Orders;

use Connectum\Models\AbstractModel;
use Connectum\Entity\Custom\OrderRebillEntityMain;

class OrderRebill extends AbstractModel
{
    protected $method = 'POST';
    protected $pathToMainData = 'tasks->{$postID}->result';
    protected $requestToFunction = '/orders/{id}/rebill';

    /**
     * @param float $amount
     * @return $this
     */
    public function rSetAmount(float $amount)
    {
        $this->payload['amount'] = $amount;
        return $this;
    }

    /**
     * @param int $cvv
     * @return $this
     */
    public function setCvv(int $cvv)
    {
        $this->payload['cvv'] = $cvv;
        return $this;
    }

    /**
     * @param string $ip
     * @return $this
     */
    public function rSetLocationIP(string $ip)
    {
        $this->payload['location']['ip'] = $ip;
        return $this;
    }

    /**
     * @param int $recurring
     * @return $this
     */
    public function setLocationIP(int $recurring)
    {
        $this->payload['location']['recurring'] = $recurring;
        return $this;
    }

    /**
     * @return OrderRebillEntityMain
     */
    public function get(): OrderRebillEntityMain
    {
        return parent::get(); // TODO: Change the autogenerated stub
    }
}
