<?php

namespace Connectum\Models\Orders;

use Connectum\Entity\Custom\OrderCancelEntityMain;
use Connectum\Models\AbstractModel;

class OrderCancel extends AbstractModel
{
    protected $method = 'PUT';
    protected $pathToMainData = 'tasks->{$postID}->result';
    protected $requestToFunction = '/orders/{id}/cancel';


    /**
     * @param int $orderID
     * @return $this
     */
    public function rSetOrderID(int $orderID)
    {
        $this->requestToFunction = str_replace('{id}', $orderID, $this->requestToFunction);
        return $this;
    }

    /**
     * @param float $amount
     */
    public function rSetAmount(float $amount)
    {
        $this->payload['amount'] = $amount;
        return $this;
    }

    /**
     * @return OrderCancelEntityMain
     */
    public function get(): OrderCancelEntityMain
    {
        return parent::get(); // TODO: Change the autogenerated stub
    }
}
