<?php

namespace Connectum\Models\Orders;

use Connectum\Entity\Custom\OrderReverseEntityMain;
use Connectum\Models\AbstractModel;

class OrderReverse extends AbstractModel
{
    protected $method = 'PUT';
    protected $pathToMainData = 'tasks->{$postID}->result';
    protected $requestToFunction = '/orders/{id}/reverse';

    /**
     * @param int $orderID
     * @return $this
     */
    public function rSetOrderID(int $orderID)
    {
        $this->requestToFunction = str_replace('{id}', $orderID, $this->requestToFunction);
        return $this;
    }

    /**
     * @return OrderReverseEntityMain
     */
    public function get(): OrderReverseEntityMain
    {
        return parent::get(); // TODO: Change the autogenerated stub
    }
}
