<?php

namespace Connectum\Models\Currency;

use Connectum\Entity\Custom\ExchangeRatesEntityMain;
use Connectum\Models\AbstractModel;

class ExchangeRates extends AbstractModel
{

    protected $method = 'GET';
    protected $pathToMainData = 'tasks->{$postID}->result';
    protected $requestToFunction = '/exchange_rates/';


    /**
     * @param string|null $from
     * @param string|null $to
     * @return $this
     */
    public function setFilterDate(string $date = null)
    {
        $this->payload['date'] = $date;
        return $this;
    }


    public function get(): ExchangeRatesEntityMain
    {
        return parent::get(); // TODO: Change the autogenerated stub
    }
}
